@CartService_HostAddress = https://localhost:8081/api/v1


GET {{CartService_HostAddress}}/cart
Accept: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTA0NDk1Ny1mNTI1LTQ0ZDItYWJhYS02Y2U3YmJmYTcwNjIiLCJlbWFpbCI6ImNtZW5hZG9lcnNAZ21haWwuY29tIiwibmFtZSI6IkNhb25hYm8gTWVuYSBQZXJleiIsIlJvbGUiOiJVc2VyIiwiYXVkIjoiZWNvc2hvcCIsImlzcyI6InVzZXJtYyIsImV4cCI6MTczMjYzNzY2NiwiaWF0IjoxNzMyNjM0MDY2LCJuYmYiOjE3MzI2MzQwNjZ9.PI9XFTJacrFZQjMEK_qFeYfPkQNyyAdTSaEVI-flAyU"

###

GET {{CartService_HostAddress}}/cart/c844b543-f864-4663-a13b-ce8fd9ea3a8e6
Accept: application/json

###

POST {{CartService_HostAddress}}/cart
Content-Type: application/json

{
  "userId": "c844b543-f864-4663-a13b-ce8fd9ea3a8e",
  "items": [
    {
      "ProductId": "de3a56bd-30df-4aed-80d8-51878a9e25a6",
      "Quantity": 10,
      "Price": 120.00
    },
    {
      "ProductId": "c4ab04a9-ea91-43ff-9814-7b288937f03f",
      "Quantity": 5,
      "Price": 799.99
    }
  ]
}

###

POST {{CartService_HostAddress}}/cart/673de818177ac53d58ce913a/items
Content-Type: application/json

{
  "ProductId": "716d7b22-cef0-4fb9-ad0d-ee37725475d3",
  "Quantity": 5,
  "Price": 500
}

###

PATCH {{CartService_HostAddress}}/cart/673de818177ac53d58ce913a/items/134004c8-57ec-4c3e-8aec-c3e35883ef75/1
Content-Type: application/json

{}
###

DELETE {{CartService_HostAddress}}/cart/673de818177ac53d58ce913a/items/134004c8-57ec-4c3e-8aec-c3e35883ef75
Accept: application/json
###


