version: '3.8'
services:
  product_db:
    image: postgres:latest
    container_name: product_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  user_db:
    image: postgres:latest
    container_name: user_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    ports:
      - '5434:5432'
    volumes:
      - pgdata_user:/var/lib/postgresql/data
  cart_db:
    image: mongo:latest
    container_name: cart_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - cartata:/etc/mongo
  ecoshop-mq:
    image: rabbitmq:3-management
    container_name: ecoshop_mq
    hostname: ecoshop-mq
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
  # user_ms:
  #    build:
  #     context: ./UserService
  #     dockerfile: Dockerfile
  #    image: ecoshop/userservice
  #    container_name: user_ms
  #    ports:
  #    - "8080:8080"
  #    - "8081:8081"
  #    environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ConnectionStrings__Default=Host=user_db;Database=userdb;User Id=admin;Password=admin;
  #    depends_on:
  #     - user_db
     

  
  

volumes:
  pgdata:
  pgdata_user:
  cartata:
