@ProductService_HostAddress = https://localhost:8082/api/v1

GET https://localhost:8082/hello
Accept: application/text

###


// CATEGORIES REQUEST
GET {{ProductService_HostAddress}}/categories
Accept: application/json

###

GET {{ProductService_HostAddress}}/categories/4af533b7-12fc-4803-a703-7d1485653358
Accept: application/json
###

POST {{ProductService_HostAddress}}/categories
Content-Type: application/json

{
  "name": "Category #2"
}

###

PATCH {{ProductService_HostAddress}}/categories/3011778b-0296-466f-9b41-affb947683d
Content-Type: application/json

{
  "name": "updated #1"
}

###

DELETE {{ProductService_HostAddress}}/categories/4706442e-ab5d-47a7-9117-4722d2e4ace7
Accept: application/json
###

POST {{ProductService_HostAddress}}/products
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "price": 20.50,
  "description": "este es un producto de prueba",
  "categoryId": "470ef532-903a-4ea5-9587-8f322e550c89",

}

###

// PRODUCTS REQUEST
PUT {{ProductService_HostAddress}}/products/4177ff9e-77b8-40c4-9706-9d8533a6bead
Content-Type: application/json
Accept: application/json

{
  "name": "product #2",
  "description": "este es un producto de prueba #2 y debe tener minimo 50 caracteres, esto es un fastidio debido a que probando cosas, no se me ocurre realmente nadca",
  "price": 50.35
}
###

DELETE {{ProductService_HostAddress}}/products/c844b543-f864-4663-a13b-ce8fd9ea3a8e
Accept: application/json
###

GET {{ProductService_HostAddress}}/products
Accept: application/json
###

GET {{ProductService_HostAddress}}/products?categoryid=fafaa776-86fd-412e-bec0-4196a86a5244
Accept: application/json
###

GET {{ProductService_HostAddress}}/products?name=laptop
Accept: application/json
###

GET {{ProductService_HostAddress}}/products?minprice=50&maxprice=1000
Accept: application/json
###

GET {{ProductService_HostAddress}}/products/de3a56bd-30df-4aed-80d8-51878a9e25a6
Accept: application/json
###


// STOCK REQUEST

GET {{ProductService_HostAddress}}/products/07e5a756-ca10-4cbe-8261-7147ab2ff001/availability
Accept: application/json
###

POST {{ProductService_HostAddress}}/products/07e5a756-ca10-4cbe-8261-7147ab2ff001/adjust-stock
Content-Type: application/json
Accept: application/json

{
  "quantity": 50,
  "reason": "Initial stock registration"
}

###

POST {{ProductService_HostAddress}}/products/07e5a756-ca10-4cbe-8261-7147ab2ff001/reserve-stock
Content-Type: application/json
Accept: application/json

{
  "quantity": 10
}

###


POST {{ProductService_HostAddress}}/products/07e5a756-ca10-4cbe-8261-7147ab2ff001/release-stock
Content-Type: application/json
Accept: application/json

{
  "quantity": 10
}

###